config_version: 0.3
genome_folder: $GENOMES
genome_servers: ['http://refgenomes.databio.org']
genomes:
  Asterochloris_sp__Cgr_DA1pho_v2_0_JGI_7_45_13:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
    genome_description: write description here
    genome_digest: d91ca3246d1581e304e36f03fb3249080af40bacd0ece16a
  Aureococcus_anophagefferens_JGI_1_0_:
    genome_description: write description here
    genome_digest: 0b93f16dce0c952e55d7f94bc64f2b3e662f68007e4baf3b
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        default_tag: default
remote_url_base: http://awspds.refgenie.databio.org/
genome_archive_folder: $GENOMES/archive
genome_archive_config: refgenie_config_archive.yaml
